services:
  - type: web
    name: intellicore-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app --chdir backend
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_SENDER
        sync: false
      - key: MAILGUN_BASE_URL
        sync: false
